config/routes.rb
Rails.application.routes.draw do
  resources :sweeps do
    resources :horses do
      put :register_horse, on: :collection
      put :assign_horse, on: :collection
    end
  end
  root "sweeps#index"
end

app/models/horse.rb
class Horse < ActiveRecord::Base

  belongs_to :sweep


  def self.find_random_horse(sp)
    if Horse.where(assigned: false).where(sweep_id: sp).count > 0
      Horse.where(assigned: false).where(sweep_id: sp).order("RANDOM()").first
    else
      nil
    end

  end

  def self.horse_count(sweep)
    Horse.where(assigned: true).where(sweep: sweep).count
    end

  def self.horses_left(sweep)
    Horse.where(sweep: @sweep).count - Horse.where(assigned: true).where(sweep: sweep).count
  end


end

app/models/sweep.rb
class Sweep < ActiveRecord::Base
  has_many :horses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  handles_sortable_columns
  before_filter :authenticate, except: [:index]

  def index
    order = sortable_column_order
    @horses = Horse.order(order)
  end

  def show
    @horses = Horse.all.order('id asc')
  end

  def edit
    @horse = Horse.find(params[:id])
  end

  def update
    @horse = Horse.find(params[:id])
    @horse.update(horse_params)
    redirect_to @horses, notice: "Updated record!"
  end

  def assign_horse
    backer = params[:horse]
    sweep = params[:sweep_id]
    horse = Horse.find_random_horse(sweep)
    if horse == nil
      redirect_to root_path, notice: "No horses left"
    else
      horse.assigned = true
      horse.bname = backer
      horse.save
      redirect_to root_path, notice: "#{horse.hname} assigned to #{horse.bname}!"
    end
  end

  def horse_params
    params.require(:horse).permit(:hname, :trainer, :odds, :assigned, :bname, :hnumber)
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "william" && password == "Infront01"
    end
  end



end

app/controllers/sweeps_controller.rb
class SweepsController < ApplicationController

  def index
    @sweeps = Sweep.all
  end

  def show
    @sweep = Sweep.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def horses_available?
    Horse.where(assigned: false)
  end

  def horses_taken?
    Horse.where(assigned: true)
  end

  def backed?(horse)
    if horse.assigned
      "info"
    end
  end

end

app/helpers/horses_helper.rb
module HorsesHelper




end

app/helpers/sweeps_helper.rb
module SweepsHelper
end

app/views/horses/_horses_available.html.erb
<div class="col-md-8">
<table class="table">
  <thead>
    <th><%= sortable_column 'ID', :column => 'id' %></th>
    <th><%= sortable_column 'Horse', :column => 'hname' %></th>
    <th><%= sortable_column 'Jockey', :column => 'trainer' %></th>
    <th><%= sortable_column 'Odds', :column => 'odds' %></th>
    <th><%= sortable_column 'Backer', :column => 'bname' %></th>
  </thead>
  <% @horses.each do |horse| %>
      <tr class=<%= backed?(horse)%>>
        <td><strong><%= horse.id %></strong></td>
        <td><strong><%= horse.hname %></strong></td>
        <td><%= horse.trainer %></td>
        <td><%= number_to_currency(horse.odds) %></td>
        <td><strong><%= horse.bname %></strong></td>
      </tr>
  <% end %>
</table>
</div>

app/views/horses/_horses_taken.html.erb
<h4>Horses taken</h4>

<table class="table table-bordered table-striped">
  <tr>
    <th>ID</th>
    <th>Horse</th>
    <th>Backer</th>
  </tr>
  <% horses_taken?.each do |horse| %>
  <tr>
    <td><%= horse.id %></td>
    <td><%= horse.hname %></td>
    <td><%= horse.bname %></td>
  </tr>
  <% end %>
</table>

app/views/horses/index.html.erb
<h1>Melbourne Cup 2014 <br>
  <small>$10 Sweep</small></h1>
<br>
<div class="row">




<%= render 'horses_available' %>

  <div class="col-md-4">
    <table class="table table-striped">
      <thead>
        <th colspan="2"><h4>Prize pool: <%= number_to_currency(Horse.horse_count * 10) %></h4></th>
      </thead>
      <tr>
          <td style="width: 20px">1st: </td>
          <td>$0 </td>
      </tr>
      <tr>
        <td>2nd: </td>
        <td>$0 </td>

      </tr>
      <tr>
        <td>3rd: </td>
        <td>$0 </td>
      </tr>
      <thead>
        <th colspan="2" style="width: 20px"><h4>Backers: <%= Horse.horse_count %></h4></th>
      </thead>
      <thead>
        <th colspan="2" style="width: 20px"><h4>Spaces left: <%= Horse.horses_left %></h4></th>
      </thead>
    </table>

    <br>
    <div>
      <h4>Some text can go here...</h4>
    </div>
  </div>


<div class="row text-right">
  <%= link_to "Admin", register_horse_sweep_horses_path, class: "btn btn-danger btn-small" %>
</div>

</div>

<br>
<br>

app/views/horses/show.html.erb
<div class="col-md-4">
  <h1>Input backer name: <%= request.original_url %> </h1>

    <%= form_tag({controller: "horses", action: "assign_horse"}, method: "put", class: "form") do %>
    <ul class="list-group">
        <li class="list-group-item">
            <%= text_field_tag(:horse) %></li>

    </ul>
    <div class="buttons"><%= submit_tag("Pick random horse", class: "btn btn-danger") %></div>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MelbourneSweeps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end -%>
<div class="container">


<%= yield %>
  </div>

</body>
</html>

app/views/sweeps/_horses_available.html.erb
<div class="col-md-8">
<table class="table">
  <thead>
    <th>ID</th>
    <th>Horse</th>
    <th>Jockey</th>
    <th>Odds</th>
    <th>Backer</th>
  </thead>
  <% @sweep.each do |sweep| %>

        <td><strong><%= sweep.horse.id %></strong></td>
        <td><strong><%= sweep.horse.hname %></strong></td>
        <td><%= sweep.horse.trainer %></td>
        <td><%= number_to_currency(sweep.horse.odds) %></td>
        <td><strong><%= sweep.horse.bname %></strong></td>
      </tr>
  <% end %>
</table>
</div>

app/views/sweeps/index.html.erb
<div class="container">
    <div class="jumbotron text-center">
      <h1>Melbourne Cup 2014</h1>
      <br>
      <p>Pick a sweep to get started...</p>
      <% @sweeps.each do |sweep| %>
        <%= link_to "$#{sweep.value} sweep", sweep_path(sweep), class: 'btn btn-primary btn-xlarge' %>
      <% end %>
    </div>
</div>

app/views/sweeps/show.html.erb
<h1>Melbourne Cup 2014 <br>
  <small>$<%= @sweep.value %> Sweep</small></h1>
<br>
<div class="row">

  <div class="col-md-8">
    <table class="table">
      <thead>
      <th>ID</th>
      <th>Horse</th>
      <th>Jockey</th>
      <th>Odds</th>
      <th>Backer</th>
      </thead>
      <% @sweep.horses.each do |horse| %>
          <tr class=<%= backed?(horse)%>>
            <td><strong><%= horse.hnumber %></strong></td>
            <td><strong><%= horse.hname %></strong></td>
            <td><%= horse.trainer %></td>
            <td><%= number_to_currency(horse.odds) %></td>
            <td><strong><%= horse.bname %></strong></td>
          </tr>
      <% end %>
    </table>
  </div>
  <div class="col-md-4">
    <table class="table table-striped">
      <thead>
      <th colspan="2"><h4>Prize pool: <%= number_to_currency(Horse.horse_count(@sweep) * 10) %></h4></th>
      </thead>
      <tr>
        <td style="width: 20px">1st: </td>
        <td>$0 </td>
      </tr>
      <tr>
        <td>2nd: </td>
        <td>$0 </td>

      </tr>
      <tr>
        <td>3rd: </td>
        <td>$0 </td>
      </tr>
      <thead>
      <th colspan="2" style="width: 20px"><h4>Backers: <%= Horse.horse_count(@sweep) %></h4></th>
      </thead>
      <thead>
      <th colspan="2" style="width: 20px"><h4>Spaces left: <%= 24 - Horse.horse_count(@sweep) %></h4></th>
      </thead>
    </table>

    <br>
    <div>
      <h4>Some text can go here...</h4>
    </div>
  </div>
</div>
<div class="row text-right">
  <%= link_to "Admin", register_horse_sweep_horses_url(@sweep), class: "btn btn-danger btn-small" %>
</div>
<br>
<br>